### ISSUE TITLE
Issues van vorige projecten

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/future-ready-design#27]
> - [originele issue](https://github.com/SamaraFellaDina/lose-your-head-the-client-case/issues/94)

Hier kan je issues vinden van vorige projecten wat betreft Future-ready-design. Misschien leuk om te kijken naar issues die nu niet reeel zijn, maar voor een opkomen project van pas kan komen.

# Wat willen we meenemen in een volgend project?

* [ ] SamaraFellaDina/lose-your-head-the-client-case#121
  * Het zou leuk zijn om verschillende kleuren te gebruiken voor het hoeveelheid fouten die worden geconstateerd bij de scan, zoals bij de lighthouse test
  * Daarbij leuk om dan het icoon grijs te houden en dan de cijfers een kleur te geven om zo te kunnen benadrukken welke fouten het ergst zijn.
  
![image](https://github.com/user-attachments/assets/88390fec-e854-4f8d-9f9a-0deae30ee017)

* [ ] SamaraFellaDina/lose-your-head-the-client-case#122 
* [ ] SamaraFellaDina/lose-your-head-the-client-case#120 
* [x] SamaraFellaDina/lose-your-head-the-client-case#40 
* [ ] https://github.com/SamaraFellaDina/future-ready-design/issues/27
* [ ] SamaraFellaDina/lose-your-head-the-client-case#127  
  * Voor een volgende keer is het een goede om de juiste uitingen uit te schetsen en dan gemakkelijk kan zetten in de `css`.
